### ISSUE TITLE
Error in Apple Store

### ISSUE THREAD

**Issue by adrpnt** [xmartlabs/cordova-plugin-market#19]
Code:
```
cordova.plugins.market.open('instagram')
```
Result
![img_0051](https://user-images.githubusercontent.com/1638815/36899210-e357d6ee-1dfc-11e8-9624-8899a2d935d3.PNG)

As the app in question is Instagram, I'm sure it exists in the store.

**Comment by adrpnt** [comment]
I solved the problem passed:
```
cordova.plugins.market.open('instagram/id389801252')
```

**Comment by najilouis** [comment]
> I solved the problem passed:
> 
> ```
> cordova.plugins.market.open('instagram/id389801252')
> ```

It works. Thanks

**Comment by coolara** [comment]
> `cordova.plugins.market.open('***') `take me 10s-20s 

> i sovled the problem passed 

> `window.location.href = "itms://****"`
