### ISSUE TITLE
Open AppStore not finding published app, while Play Store does

### ISSUE THREAD

**Issue by guillermoap** [xmartlabs/cordova-plugin-market#20]
Hello. 

I'm having no problems opening the Play Store from the app, but when I run it on iOS with the same package name, the AppStore returns an 'app not found' response. I've checked the apps bundle identifier with Xcode and it's `com.appName.app`. That bundle id works for the Play Store but not for the App Store.

I'm calling the method as explained in the doc: `this.market.open('com.appName.app');`

I don't know if I'm doing anything wrong in regards to using the plugin or if something is not working properly.

**Comment by diebarral** [comment]
I'm having the same  issue here, any response? Is anybody doing maintenance on this plugin?

**Comment by camilosw** [comment]
This was solved here #19 

If your url is `https://itunes.apple.com/co/app/instagram/id389801252?l=en&mt=8` your identifier is `instagram/id389801252`.

The correct way to call the method is `this.market.open('instagram/id389801252');`
