### ISSUE TITLE
Open link in Google play market inside Mobomarket

### ISSUE THREAD

**Issue by YaroslavG** [xmartlabs/cordova-plugin-market#6]
Hello.
I use your plugin and it is work fine but when I download MoboMarket to my phone after click app open MoboMarket app. I do not want open this app. I want open my link in Google Play.

Do you have solution how do it?
Thanks

**Comment by enrigalmig** [comment]
That's weird, the way is implemented call the intent to open market… maybe you had MoboMarket as default. Did you try it in other devices?

**Comment by m-revetria** [comment]
no more info was provided
